### ISSUE TITLE
Cellular Network Not Working Properly

### ISSUE THREAD

**Issue by tanujboy** [Nevax07/FreedomOS#14]
I flashed Freedom OS 1.5.0 on my OnePlus 3 and (accidentally) switched off the phone while it was booting up with the power button.

After that the cellular network doesn't work properly, sometimes full signal, sometimes no signal (On the same place), sometimes I can call, but most of the time I can't, sometimes I can receive texts but most of the times I can't. And the data never works.

I tried doing a clean wipe and installing Resurrection Remix 5.7.4, Oxygen OS 3.2.6, CyanogenMod 13 but it doesn't work on any ROM.

Also, the MTP is also not working now on CM based ROMs but it works on Oxygen OS. Before this, the fingerprint sensor/home button also didn't use to work on Resurrection Remix but that got fixed after I flashed Freedom OS 1.4.4 (Thank you NevaX for the help with that).

Please help because without the cellular network working properly, I am basically limited. 

Should I flash the initial builds like 1.0.1, 1.1, 1.1.1 etc in order to get the cellular network working? Does Freedom OS replace some of the important OnePlus 3 firmware files?

**Comment by Nevax07** [comment]
Hi @tanujboy,

i refuse all pull requests and issues coming from Github, use Gitlab.
https://gitlab.com/Nevax/FreedomOS

Have a nice day :)

**Comment by Nevax07** [comment]
I let the issue tracker open to let you see my comment.
After that, i will remove the issue tab rom github.
GitHub is only a mirror, i work on gitlab.
